apiVersion: v1
kind: Pod
metadata:
  name: kube-app
spec:
  serviceAccountName: kube-app
  containers:
    - name: kube-app
      image: ubuntu:latest
      volumeMounts:
      - name: config-volume
        mountPath: /app/config.sh
        subPath: config.sh
  volumes:
    - name: config-volume
      configMap:
        name: app-config
  restartPolicy: Never
